sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t titoeb/test-docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true titoeb/test-docker-react npm run test -- --coverage
